pipeline {
    agent any
    environment {
        HOST = 'localhost'
        PORT = 3000
        DB_PORT = 5432
        DB_HOST = 'postgres'
        DB_USER = 'postgres'
        DB_PASS = 'postgres'
        DATABASE = 'bookstore'
        MODE = 'production'
        DB_SYNC = 'true'
        DB_LOGGING = 'true'
    }
    tools { 
        nodejs "node"
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/<USER>/<REPO_URL>', branch: 'master'
            }
        }
        stage('Install and build application') {
            steps {
                sh 'node --version'
                sh 'npm --version'
                sh 'npm install'
                sh 'npm run build'
                sh 'npm run start:prod'
                sh 'docker --version'
                sh 'docker-compose --version'
                //sh 'kill -15 $(pgrep -g $(cat pid))'
                //sh 'docker-compose -f docker-compose.yml up -d postgres'
            }
        }
    }
}

