pipeline {
    agent any
    environment {
        HOST = 'localhost'
        PORT = 3000
        DB_PORT = 5432
        DB_HOST = 'postgres'
        DB_USER = 'postgres'
        DB_PASS = 'postgres'
        DATABASE = 'bookstore'
        MODE = 'production'
        DB_SYNC = 'true'
        DB_LOGGING = 'true'
    }
    tools { 
        nodejs "node"
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/<USER>/<REPO_URL>', branch: 'master'
            }
        }
        stage('Install and build application') {
            steps {
                sh 'node --version'
                sh 'npm --version'
                sh 'npm install'
                sh 'npm run build'
                sh 'npm run test'
                // Remove client build from Dockerfile
                // NOTE: things have to be double escaped for sed to escape them
                sh "sed -i '/RUN npm --prefix \\.\\/client.*/d' Dockerfile"
                sh 'make build'
                sh 'docker-compose -f docker-compose.yml up -d postgres'
                sleep 3
                sh 'docker-compose -f docker-compose.yml up -d application'
                sleep 2
                sh 'make test'
                sh 'make e2e'
            }
        }
    }
  post {
      always {
          sh 'make clean'
      }
  }
}

