export enum AlertConstants {
  PRODUCT_ADDED = 'PRODUCT_ADDED',
  PRODUCT_DELETED = 'PRODUCT_DELETED',
  CART_CLEARED = 'CART_CLEARED',
  LOGGED_IN = 'LOGGED_IN',
  REGISTERED = 'REGISTERED',
  HIDEOUT = 'HIDEOUT',
}
