export const UserConstants = {
  SET_MESSAGE: 'SET_MESSAGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',

  REGISTER_REQUEST: 'REGISTER_ REQUESTING',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUESTING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  VIEW_USERS: 'VIEW_USERS',

  LOGOUT: 'LOGOUT',
  ROLE: 'ROLE',
};
