/*
export enum PromotionConstants {
  CREATE_PROMOTION_BEGIN = 'CREATE_PROMOTION_BEGIN',
  CREATE_PROMOTION_SUCCESS = 'CREATE_PROMOTION_SUCCESS',
  CREATE_PROMOTION_FAILURE = 'CREATE_PROMOTION_FAILURE',

  REMOVE_PROMOTION_BEGIN = 'REMOVE_PROMOTION_BEGIN',
  REMOVE_PROMOTION_SUCCESS = 'REMOVE_PROMOTION_SUCCESS',
  REMOVE_PROMOTION_FAILURE = 'REMOVE_PROMOTION_FAILURE',

  FETCH_PROMOTION_BEGIN = 'FETCH_PROMOTION_BEGIN',
  FETCH_PROMOTION_SUCCESS = 'FETCH_PROMOTION_SUCCESS',
  FETCH_PROMOTION_FAILURE = 'FETCH_PROMOTION_FAILURE',
}
*/
