export enum ProductConstants {
  FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN',
  FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE',

  SEARCH_PRODUCTS_BEGIN = 'SEARCH_PRODUCTS_BEGIN',
  SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS',
  SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE'
}
