export enum ProductConstants {
  FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN',
  FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE',

  SEARCH_PRODUCTS_BEGIN = 'SEARCH_PRODUCTS_BEGIN',
  SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS',
  SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE',

  CREATE_PRODUCT_BEGIN = 'CREATE_PRODUCT_BEGIN',
  CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE',

  UPDATE_PRODUCT_BEGIN = 'UPDATE_PRODUCT_BEGIN',
  UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE',

  REMOVE_PRODUCT_BEGIN = 'REMOVE_PRODUCT_BEGIN',
  REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS',
  REMOVE_PRODUCT_FAILURE = 'REMOVE_PRODUCT_FAILURE',
}
