export const NEW_RELEASES_DATA = [
  {
    id: 1,
    title: 'Brown Brim',
    image: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
    price: 25,
    quantity: 1,
  },
  {
    id: 2,
    title: 'Blue Beanie',
    image: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
    price: 18,
    quantity: 1,
  },
  {
    id: 3,
    title: 'Brown Cowboy',
    image: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
    price: 35,
    quantity: 1,
  },
  {
    id: 4,
    title: 'Grey Brim',
    image: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
    price: 25,
    quantity: 1,
  },
  {
    id: 5,
    title: 'Green Beanie',
    image: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
    price: 18,
    quantity: 1,
  },
  {
    id: 6,
    title: 'Palm Tree Cap',
    image: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
    price: 14,
    quantity: 1,
  },
  {
    id: 7,
    title: 'Red Beanie',
    image: 'https://i.ibb.co/bLB646Z/red-beanie.png',
    price: 18,
    quantity: 1,
  },
  {
    id: 8,
    title: 'Wolf Cap',
    image: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
    price: 14,
    quantity: 1,
  },
  {
    id: 9,
    title: 'Blue Snapback',
    image: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
    price: 16,
    quantity: 1,
  },
];
